#!/bin/sh

# pnd-crashreporter-namespace.sh
# Generates a prefix header to namespace all Firebase Crashlytics symbols
# to avoid collisions with the real Firebase SDK.

function generate_header()
{
    local HEADER_LOCATION="${1}"
    local BINARY_PATH="${2}"
    
    echo "==========================================================================================================="
    echo "▸ 01 - Delete generated header if it exists"
    echo "==========================================================================================================="
    [ -e "$HEADER_LOCATION" ] && rm "$HEADER_LOCATION"
    
    echo "======================================================================================================="
    echo "▸ 02 - Generate combined header"
    echo "======================================================================================================="
    echo "▸ HEADER_LOCATION: ${HEADER_LOCATION}"
    echo "▸ BINARY_PATH    : ${BINARY_PATH}"
    
    cat << 'EOF' > "$HEADER_LOCATION"
//
// Copyright 2024 Pendo inc.
// This file has been automatically generated by Pendo's namespacing script.
//

#ifndef PNDCrashReporter_Namespace_h
#define PNDCrashReporter_Namespace_h

// Namespaced Header
#ifndef __PENDO_NAMESPACE_PREFIX_
#define __PENDO_NAMESPACE_PREFIX_ PND
#endif

// MACROS
#ifndef __PENDO_NS_SYMBOL
#define __PENDO_NS_REWRITE(namespace,symbol) namespace ## _ ## symbol
#define __PENDO_NS_BRIDGE_(namespace,symbol) __PENDO_NS_REWRITE(namespace,symbol)
#define __PENDO_NS_SYMBOL(symbol) __PENDO_NS_BRIDGE_(__PENDO_NAMESPACE_PREFIX_,symbol)
#endif
// MACROS END

EOF

    # The actual extraction logic will go here
    echo "// Classes"       >> "$HEADER_LOCATION"
    nm "$BINARY_PATH" -j | sort | uniq | grep "^_OBJC_CLASS_\$_FIR" | grep -v '\$_NS' | grep -v '\$_UI' | grep -v '\$_CA' | sed -e 's/_OBJC_CLASS_\$_\(.*\)/#ifndef \1\'$'\n''#define \1 __PENDO_NS_SYMBOL(\1)\'$'\n''#endif/g' >> "$HEADER_LOCATION"
    echo "// Classes END"   >> "$HEADER_LOCATION"
    echo ""                 >> "$HEADER_LOCATION"

    echo "// C Functions and Globals" >> "$HEADER_LOCATION"
    nm "$BINARY_PATH" -j | sort | uniq | grep -E "^_[Ff][Ii][Rr][A-Za-z0-9_]*$" | sed -e 's/_\(.*\)/#ifndef \1\'$'\n''#define \1 __PENDO_NS_SYMBOL(\1)\'$'\n''#endif/g' >> "$HEADER_LOCATION"
    echo "// C Functions and Globals END" >> "$HEADER_LOCATION"
    echo ""                 >> "$HEADER_LOCATION"


    
    echo "#endif /* PNDCrashReporter_Namespace_h */" >> "$HEADER_LOCATION"
    
    echo "======================================================================================================="
    echo "▸ Finished namespace header generation"
    echo "======================================================================================================="
}

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <path-to-binary> <path-to-output-header>"
    exit 1
fi

generate_header "$2" "$1"
